#!/bin/bash

convert zoomin_location_of_profiles2004.jpg -trim zoomin_location_of_profiles2004-trimmed.jpg
convert zoomin_location_of_profiles2005.jpg -trim zoomin_location_of_profiles2005-trimmed.jpg
convert zoomin_location_of_profiles2006.jpg -trim zoomin_location_of_profiles2006-trimmed.jpg
convert zoomin_location_of_profiles2007.jpg -trim zoomin_location_of_profiles2007-trimmed.jpg
convert zoomin_location_of_profiles2008.jpg -trim zoomin_location_of_profiles2008-trimmed.jpg
convert zoomin_location_of_profiles2009.jpg -trim zoomin_location_of_profiles2009-trimmed.jpg
convert zoomin_location_of_profiles2010.jpg -trim zoomin_location_of_profiles2010-trimmed.jpg
convert zoomin_location_of_profiles2011.jpg -trim zoomin_location_of_profiles2011-trimmed.jpg
convert zoomin_location_of_profiles2012.jpg -trim zoomin_location_of_profiles2012-trimmed.jpg
convert zoomin_location_of_profiles2013.jpg -trim zoomin_location_of_profiles2013-trimmed.jpg
convert zoomin_location_of_profiles2014.jpg -trim zoomin_location_of_profiles2014-trimmed.jpg
convert zoomin_location_of_profiles2015.jpg -trim zoomin_location_of_profiles2015-trimmed.jpg
convert zoomin_location_of_profiles2016.jpg -trim zoomin_location_of_profiles2016-trimmed.jpg
convert zoomin_location_of_profiles2017.jpg -trim zoomin_location_of_profiles2017-trimmed.jpg
